add chinese trraditional verion for taiwan
angular/angular-update-guide pull request #108
Opened 2021-02-07 16:11 UTC by tso1158687

add chinese traditional version for taiwan
this translation depends on

- translation on angular.tw
- change link from angular.io to angular.tw

2021-04-19 13:21 UTC, tomyjwu reviewed
翻譯是很主觀的，僅提供一些意見供參考。

2021-04-19 13:21 UTC, tomyjwu commented on src/app/locales/zh_TW.ts
> +    action: '對於 Angular 表單驗證，`minLength` 和 `maxLength` 驗證器現在在正表單控制組件具有數字長度的屬性，且唯有在此情況下才會驗證長度。'
對於 Angular 表單驗證，表單控件的值的長度 (length) 屬性是數字類別時，`minLength` 和 `maxLength` 驗證器才會對此控件做長度驗證。

2021-04-19 22:27 UTC, mgechev commented
@tso1158687 would you have a look at the comments by @tomyjwu? We can merge once you address them :)

2021-04-20 14:49 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +    action: '當將時間日期包含毫秒的字串的格式傳送給 `DatePipe` 時，現在毫秒將會四捨入，而非取最接近的毫秒。大多數的應用程式將會不受此更改影響。如果這不是你預期的行為，那麼考慮對字串先行處理四捨五入至毫秒再傳送給 `DatePipe`。'
已修正，打到昏頭了

2021-04-20 14:49 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +    action: '`async` 管道不再要求輸入為 undefined 的輸入返回 undefined。要注意的是，程式碼實際上在位定義的輸入返回 null。'
已修正錯字

2021-04-20 14:49 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +    action: '對於 Angular 表單驗證，`minLength` 和 `maxLength` 驗證器現在在正表單控制組件具有數字長度的屬性，且唯有在此情況下才會驗證長度。'
謝謝，當初想了好久，這樣翻譯順多了

2021-04-20 14:50 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +    action: '停止傳遞任何參數給 ErrorHandler 的建構式'
既然在angular.tw都稱為建構函式，那麼就以angular.tw的翻譯為準吧!

2021-04-20 14:53 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +      '当你包含 `FormsModule` 时，Angular 开始向表单元素添加一个 `novalidate` 属性，重新启用原始(Native)表单验证使用 `ngNoForm` 或添加 `ngNativeValidate`。'
謝謝，應該是校對的時候蓋掉原本的了

2021-04-20 14:54 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +  'App Complexity': '程式複雜度',
統一稱為應用程式

2021-04-20 14:55 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +    '目前在这两个版本间变化无需任何变更目前這兩個版本間的變化。',
謝謝，應該是校對的時候不小心貼到了

2021-04-20 14:56 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +    action: '替换从 `@angular/upgrade` 导入的 `downgradeComponent`、`downgradeInjectable`、`UpgradeComponent` 和 `UpgradeModule`。需要在 `@angular/upgrade/static` 中使用新版本'
謝謝，應該在校對的時候貼到了

2021-04-20 15:07 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +    '顯示所有與Angular 開發人員相關更新資訊。',
顯示 Angular 開發人員都要知道的更新資訊。

2021-04-20 15:07 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +    '顯示大約關於10% Angular 開發人員相關詳細更新資訊。',
顯示約前10% Angular 開發人員詳細更新資訊。

2021-04-20 15:08 UTC, tso1158687 commented on src/app/locales/zh_TW.ts
> +    action: '在測試中，如果在 TestBed 初始化後呼叫 `TestBed.overrideProvider`，overrideProvider 已移除。此行為與其他替代方法(例如 `TestBed.overrideDirective` 等)一致，但會拋出錯誤指出這點。此檢查以前在 TestBed.overrideProvider 函數中錯失。如果看到該錯誤，應該在 TestBe
謝謝這樣好像比較順

2021-04-20 15:15 UTC, tso1158687 commented
@googlebot I signed it!

2021-04-20 15:22 UTC, tso1158687 commented
@googlebot I fixed it.

2021-04-20 15:48 UTC, mgechev commented
@tso1158687 looks like the CLA bot is unhappy because of [this](https://github.com/angular/angular-update-guide/pull/108/commits/45edbb06d3549f57f7e9ef7bb43ad77d7a4b887c) commit. If it's part of your contribution you can squash it as part of another commit, or drop it alternatively.

After that we should be able to merge your PR.

Please, directly mention me once you're done to make sure I don't miss the notification. :)

2021-04-21 14:50 UTC, tso1158687 commented
Hi @mgechev,
I have squashed and forced push the commit and all checks have passed.

Please help me to merge this commit into master.

Thank you!

2021-04-21 15:00 UTC, doggy8088 commented
Hi @tso1158687 , could you take a look of my reviews? There are some words needs to be revised.

2021-04-21 17:24 UTC, doggy8088 requested changes

2021-04-22 15:11 UTC, tomyjwu commented
> @mgechev sure!
> I have updated translation by @tomyjwu advices

thanks. changes looks to me . +1

2021-04-22 15:14 UTC, tomyjwu commented
@tso1158687 請再確認一下保哥的comments 即可。

2021-04-22 15:16 UTC, doggy8088 approved these changes
LGTM

2021-04-22 16:39 UTC, tso1158687 commented
@tomyjwu @doggy8088  yes I resolved all comments in this [commit](https://github.com/angular/angular-update-guide/pull/108/commits/832a61de4a93110e007e61f0fe1a87005321a54d)

@mgechev please help me to merge into master.
Thank you all!

2021-04-26 01:13 UTC, tomyjwu approved these changes
LGTM

2021-04-26 02:19 UTC, mgechev approved these changes

2021-04-26 02:19 UTC, merged

2021-04-26 02:19 UTC, mgechev commented
Thank you for the translation!